services:
  - type: web
    name: evamed
    env: python
    plan: free
    buildCommand: "cd frontend && rm -rf dist node_modules && npm install && npm run build && cd .. && pip install -r requirements.txt"
    startCommand: "uvicorn backend.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: RENDER
        value: "true"
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: ADMIN_PASS
        value: "evamed2024"
